name: uoi-crs01
channels:
  - defaults
dependencies:
  - _nb_ext_conf=0.4.0=py36_1
  - anaconda-client=1.6.14=py36_0
  - asn1crypto=0.24.0=py36_0
  - backcall=0.1.0=py36_0
  - bleach=2.1.3=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36h9745a5d_0
  - chardet=3.0.4=py36h0f667ec_1
  - clyent=1.2.2=py36h7e57e65_1
  - cryptography=2.2.2=py36h14c3975_0
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36h1aec115_2
  - gmp=6.1.2=h6c8ec71_1
  - html5lib=1.0.1=py36h2f9c1c0_0
  - idna=2.6=py36h82fb2a8_1
  - ipykernel=4.8.2=py36_0
  - ipython=6.3.1=py36_0
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - ipywidgets=7.2.1=py36_0
  - jedi=0.12.0=py36_1
  - jinja2=2.10=py36ha16c418_0
  - jsonschema=2.6.0=py36h006f8b5_0
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py36h7c827e3_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - markupsafe=1.0=py36hd9260cd_1
  - mistune=0.8.3=py36h14c3975_1
  - nb_anacondacloud=1.4.0=py36_0
  - nb_conda=2.2.1=py36h8118bb2_0
  - nb_conda_kernels=2.1.0=py36_0
  - nbconvert=5.3.1=py36hb41ffb7_0
  - nbformat=4.4.0=py36h31c9010_0
  - nbpresent=3.0.2=py36h5f95a39_1
  - ncurses=6.0=h9df7e31_2
  - notebook=5.4.1=py36_0
  - openssl=1.0.2o=h20670df_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py36ha6701b7_1
  - parso=0.2.0=py36_0
  - pexpect=4.5.0=py36_0
  - pickleshare=0.7.4=py36h63277f8_0
  - pip=10.0.1=py36_0
  - plotly=2.5.1=py36_0
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - pycparser=2.18=py36hf9f622e_1
  - pygments=2.2.0=py36h0d3125c_0
  - pyopenssl=17.5.0=py36h20ba746_0
  - pysocks=1.6.8=py36_0
  - python=3.6.5=hc3d631a_2
  - python-dateutil=2.7.2=py36_0
  - pytz=2018.4=py36_0
  - pyyaml=3.12=py36hafb9ca4_1
  - pyzmq=17.0.0=py36h14c3975_0
  - readline=7.0=ha6073c6_4
  - requests=2.18.4=py36he2e5f8d_1
  - send2trash=1.5.0=py36_0
  - setuptools=39.1.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - six=1.11.0=py36h372c433_1
  - sqlite=3.23.1=he433501_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h8cadb63_0
  - tk=8.6.7=hc745277_3
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36h674d592_0
  - urllib3=1.22=py36hbe7ace6_0
  - wcwidth=0.1.7=py36hdf4376a_0
  - webencodings=0.5.1=py36h800622e_1
  - wheel=0.31.0=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - xz=5.2.3=h5e939de_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=h439df22_0
  - zlib=1.2.11=ha838bed_2
  - pip:
    - astroid==1.6.3
    - ikp3db==1.1.4
    - isort==4.3.4
    - lazy-object-proxy==1.3.1
    - mccabe==0.6.1
    - pylint==1.8.4
    - pylint-django==0.11
    - pylint-plugin-utils==0.2.6
    - virtualenv==15.2.0
    - wrapt==1.10.11
prefix: /home/loganjtravis/miniconda3/envs/uoi-crs01

